config/routes.rb
Rails.application.routes.draw do

  devise_for :users, class_name: 'FormUser', :controllers => { registrations: 'registrations',
                   omniauth_callbacks: 'omniauth_callbacks'}
  resources :admin_users, controller: 'users'
  resources :categories do
    collection do
      put :sort, to: 'categories#sort'
    end
    resources :posts, except: [:new, :create, :index] do
      resources :comments, only: [:create, :destroy]
    end
  end
  resources :posts, only: [:new, :create]
  resources :topics do
    resources :forum_posts, only: [:create, :destroy] do
      member do
        put :like, to: 'forum_posts#upvote'
        put :dislike, to: 'forum_posts#downvote'
      end
    end
  end
  get 'search', to: 'homes#search'
  root 'homes#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :omniauthable

  has_many :posts, dependent: :nullify
  has_many :comments, dependent: :nullify
  has_many :forum_posts, dependent: :nullify
  has_many :identities, dependent: :destroy

  scope :moderators, -> { where(role: 1)}
  #scope :find_by_first_or_last_name, -> { |q| where('first_name like ? or last_name like ?', "%#{q}%","%#{q}%") }

  validates_presence_of :first_name, :last_name, :email, :password
  validates_format_of :email, with: Devise::email_regexp

  enum role: [:guest, :moderator, :admin]

  def name
    "#{first_name} #{last_name}"
  end

  def to_s
    puts "#{name} - #{email} - #{password} - #{encrypted_password}"
  end

  def posts_with_category
     self.posts.includes(:category)
  end

  def self.find_by_first_or_last_name(q)
    where('first_name like ? or last_name like ?', "%#{q}%","%#{q}%")
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: :show
  before_action :set_user, except: [:index, :new, :create]

  def index
    @users = User.all
    @users = @users.where(role: params[:role]) if params[:role].present?
    @users = @users.find_by_first_or_last_name(params[:q]) if params[:q].present?
    @users = @users.paginate(page: params[:page], per_page: 10)
    respond_to do |format|
        format.html { }
        format.js {}
    end
  end

  def show
    authorize @user
  end

  def new
    authorize User
    @user = User.new
  end

  def create
    @user = User.new
    @user.update(permitted_attributes(@user))
    authorize @user
    if  @user.save
      redirect_to admin_users_path, notice: 'User created successfully'
    else
      render 'new'
    end
  end

  def edit
    authorize @user
  end

  def update
    authorize @user
    if @user.update(permitted_attributes(@user))
      redirect_to admin_users_path, notice: 'New user created successfully'
    else
      render 'edit'
    end
  end

  def destroy
    authorize @user
    @user.destroy
    redirect_to admin_users_path, notice: 'User deleted successfully'
  end

  private

  def user_params
    params.require(:user).permit(:email, :first_name, :last_name, :password, :role)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="user">
  <%= form_for([:admin, @user]) do |f| %>
      <% if @user.errors.any? %>
          <div class="form_errors">
              <h4> <%= pluralize(@user.errors.size, 'error')%> prohibited this data from being saved</h4>
              <ul>
                <% @user.errors.full_messages.each do |msg| %>
                    <li> <%= msg %> </li>
                <% end %>
              </ul>
          </div>
      <% end %>
    <div class="form-group row">
      <%= f.label :first_name, class: 'col-sm-2 form-control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :first_name, class: 'form-control', placeholder: 'First Name' %>
      </div>
    </div>
    <div class="form-group row">
        <%= f.label :last_name, class: 'col-sm-2 form-control-label' %>
        <div class="col-sm-10">
            <%= f.text_field :last_name, class: 'form-control', placeholder: 'Last Name' %>
        </div>
    </div>
      <div class="form-group row">
        <%= f.label :email, class: 'col-sm-2 form-control-label' %>
        <div class="col-sm-10">
        <%= f.email_field :email, class: 'form-control', placeholder: 'Email' %>
          </div>
      </div>
      <div class="form-group row">
        <%= f.label :password, class: 'col-sm-2 form-control-label' %>
        <div class="col-sm-10">
        <%= f.password_field :password, class: 'form-control', placeholder: 'Password' %>
          </div>
      </div>
      <div class="form-group row">
        <%= f.label :role, class: 'col-sm-2 form-control-label', placeholder: 'Role' %>
        <div class="col-sm-10">
        <%= f.select(:role, User.roles.keys.map{|role| [role.titleize, role]}, {class: 'form-control'}) %>
          </div>
      </div>
      <div class="form-group row">
        <%= f.submit class:'button_my' %>
      </div>
  <% end %>
</div>

app/views/users/_guest.html.erb
<p> <strong>Type:</strong> <small> <%= user.role.to_s.capitalize %> </small></p>
<p><strong>Member since:</strong> <%= user.created_at.strftime("%b/%Y") %></p>
<p><strong>Number of signings:</strong> <%= user.sign_in_count %> </p>
<p><strong>Last sign in:</strong> <%= user.last_sign_in_at.strftime("%d/%b/%Y / %H:%M") %> </p>
<p><strong>Last IP address:</strong> <%= user.last_sign_in_ip %> </p>
<% if user_signed_in? && current_user.admin? %>
    <%= link_to 'Edit', edit_admin_user_path(user)%> |
    <%= link_to 'Delete', admin_user_path(user), method: :delete, data: {confirm: 'Are you sure?'} %>
<% end %>

app/views/users/_moderator.html.erb
<% if user_signed_in? && current_user.admin? %>
    <strong>Manage user: </strong>
    <%= link_to 'Edit', edit_admin_user_path(user)%> |
    <%= link_to 'Delete', admin_user_path(user), method: :delete, data: {confirm: 'Are you sure?'} %>
    <hr/>
<% end %>
<p> <strong>Posts published:</strong> <%= user.posts.size %> </p>
<% if user.posts.present? %>
    <p><strong> Last post:</strong> <%= time_ago_in_words user.posts.last.created_at %> ago </p>
    <br/>
    <h4> Posts archive: </h4>
    <hr/>
    <%= render partial: 'posts/mini_post', collection: user.posts_with_category, as: :post %>
<% end %>

app/views/users/_sidebar.html.erb
<%= button_to new_admin_user_path, method: :get, class: 'button_my' do %>
    <i class="fa fa-plus" aria-hidden="true"></i>
    <span>Create New User</span>
<% end %>
<hr/>
<h4>Filter results</h4>
<hr class="line"/>
<div class="search">
    <input id="q" type="text" placeholder="Search for a user.."> <button id="search_button">Search</button>
</div>
<hr/>
<%= check_box_tag 'guest', admin_users_path(role: 0) %> Show only guests <br/>
<%= check_box_tag 'worker', admin_users_path(role: 1) %> Show only moderators <br/>
<%= check_box_tag 'admin', admin_users_path(role: 2) %> Show only admins
<hr/>

app/views/users/_user.html.erb
<div class="user">
  <h4><%= link_to user.name, admin_user_path(user) %></h4>
  <p><strong>Type:</strong> <%= user.role %> </p>
  <% if policy(user).update? %>
    <%= link_to 'Edit', edit_admin_user_path(user)%> |
    <%= link_to 'Delete', admin_user_path(user), method: :delete, data: {confirm: 'Are you sure?'} %>
  <% end %>
  <hr/>
</div>

app/views/users/edit.html.erb
<h3>Edit User</h3>
<hr class="line"/>
<div class="main_content">
    <%= render 'form' %>
    <%= link_to 'Back to all users', admin_users_path %>
</div>

app/views/users/index.html.erb
<h3>All Users</h3>
<hr class="line"/>
<div class="main_content">
    <div class="users">
      <% if @users.size > 0 %>
        <%= render @users %>
      <%= will_paginate @users, renderer: BootstrapPagination::Rails %>
          <% else %>
        <p>No users that match this criteria.</p>
      <% end %>
    </div>
</div>
<div class="sidebar">
  <%= render 'sidebar' %>
</div>

app/views/users/index.js.erb
$('div.users').empty();
<% if @users.size > 0%>
    $('div.users').append(' <%= j render @users %> ');
    $('div.users').append(' <%= j will_paginate @users, renderer: BootstrapPagination::Rails  %> ');
<% else %>
$('div.users').append('<p>No users that match this criteria</p>');
<% end %>

app/views/users/new.html.erb
<h3>New user</h3>
<hr class="line"/>
<div class="main_content">
    <%= render 'form' %>
</div>

app/views/users/show.html.erb
<p class="main_title"> Archive:  <%= @user.name %> </p>
<hr class="line"/>
<div class="main_content">
  <% if @user.moderator? %>
      <%= render partial: 'moderator', locals: {user: @user}%>
  <% elsif @user.guest? %>
      <%= render partial: 'guest', locals: {user: @user}%>
  <% else %>
      <h4> <%= @user.name %> </h4>
  <% end %>
</div>
<div class="sidebar">
  <h4>Other moderators</h4>
  <hr class="line"/>
  <ul>
    <% User.moderators.each do |moderator| %>
        <li> <%= link_to moderator.name, admin_user_path(moderator)%> </li>
    <% end %>
  </ul>
</div>