config/routes.rb
Rails.application.routes.draw do

  devise_for :users, class_name: 'FormUser', :controllers => { registrations: 'registrations',
                   omniauth_callbacks: 'omniauth_callbacks'}
  resources :admin_users, controller: 'users'
  resources :categories do
    collection do
      put :sort, to: 'categories#sort'
    end
    resources :posts, except: [:new, :create, :index] do
      resources :comments, only: [:create, :destroy]
    end
  end
  resources :posts, only: [:new, :create]
  resources :topics do
    resources :forum_posts, only: [:create, :destroy] do
      member do
        put :like, to: 'forum_posts#upvote'
        put :dislike, to: 'forum_posts#downvote'
      end
    end
  end
  get 'search', to: 'homes#search'
  root 'homes#index'

end

app/models/forum_post.rb
class ForumPost < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
  belongs_to :topic, counter_cache: true

  validates_presence_of :content

  def user_name
    self.user.name
  end


end

app/controllers/forum_posts_controller.rb
class ForumPostsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_topic
  before_action :set_forum_post, only: [:destroy, :upvote, :downvote]


  def create
    authorize ForumPost
    @forum_post =  @topic.forum_posts.build(forum_post_params)
    @forum_post.user_id = current_user.id
    respond_to do |format|
      if @forum_post.save
        format.js { }
      else
        format.js { render 'create_with_error' }
      end
    end
  end

  def destroy
    authorize @forum_post
    @forum_post.destroy
    respond_to do |format|
      format.html { redirect_to @topic }
      format.js { }
    end
  end

  def upvote
    authorize @forum_post
    @forum_post.liked_by current_user
    redirect_to :back
  end

  def downvote
    authorize @forum_post
    @forum_post.downvote_from current_user
    redirect_to :back
  end

  private

  def forum_post_params
    params.require(:forum_post).permit(:content)
  end

  def set_forum_post
    @forum_post = @topic.forum_posts.find(params[:id])
  end

  def find_topic
    @topic = Topic.friendly.find(params[:topic_id])
  end
end

app/helpers/forum_posts_helper.rb
module ForumPostsHelper
end

app/views/forum_posts/_form.html.erb
<h4>Make a post on this topic</h4>
<hr class="line"/>
<%= form_for [@topic, @topic.forum_posts.build], {remote: true} do |f| %>
    <div class="field">
        <%= f.text_area :content, rows: 5, cols: 30, placeholder: 'Your post*' %>
    </div>
    <div class="actions">
      <%= f.submit 'Add Post', class: 'forum_post_button' %>
    </div>
<% end %>

app/views/forum_posts/_forum_post.html.erb
<div class="forum_post" data-id="<%= forum_post.id %>">
  <% if forum_post.user.nil? %>
      <strong> Unknown:</strong>
  <% else %>
      <strong><%= forum_post.user_name %>:</strong>
  <% end %>
  <% if user_signed_in? && current_user.admin?%>
    <span id="dlt_f_post" class="pull-right" data-url="<%= topic_forum_post_path(forum_post.topic, forum_post)%>"><i class="fa fa-times fa-lg"></i></span>
  <% end %>
  <br/>
  <span class="date_of_posting"> <%= forum_post.created_at.strftime("%m/%d/%Y") %> </span>
  <div class="content"> <%= simple_format forum_post.content %> </div>
  <br/>
  <div class="voting">
    <% if user_signed_in? %>
      <%= link_to like_topic_forum_post_path(forum_post.topic, forum_post), method: :put do  %>
            <span class="glyphicon glyphicon-thumbs-up like"></span>
      <% end %>
    <% else %>
        <span class="glyphicon glyphicon-thumbs-up like"></span>
    <% end %>
      <span> <%= forum_post.cached_votes_up %> </span>
    <% if user_signed_in? %>
      <%= link_to dislike_topic_forum_post_path(forum_post.topic, forum_post), method: :put do  %>
          <span class="glyphicon glyphicon-thumbs-down dislike"></span>
      <% end %>
    <% else %>
        <span class="glyphicon glyphicon-thumbs-down dislike"></span>
    <% end %>
      <span> <%= forum_post.cached_votes_down %> </span>
  </div>

  <hr/>
</div>

app/views/forum_posts/create.js.erb
if($('div.empty_msg').length > 0) {
    $('div.empty_msg').remove();
    $('div.forum_posts').append(' <%= j render @forum_post %> ');
} else {
    if($('div.forum_post').size() >= 10 && ($('div.pagination').length != 0)) {
        $('button#more_forum_posts').after(' <h5 id="message">Post created successfully</h5> ');
        $('h5#message').delay(3000).fadeOut();
    }
    else {
        $('div.forum_post:last').after('<%= j render @forum_post %>');
    }
}
$('textarea#forum_post_content').val('');

app/views/forum_posts/create_with_error.js.erb
console.log("has errors");
$('form#new_forum_post').before('<h5 id="error_msg">Write your post first.</h5>');

app/views/forum_posts/destroy.js.erb
$('div[data-id="<%= @forum_post.id%>"]').fadeOut(500, function(){ $(this).remove(); });