config/routes.rb
Rails.application.routes.draw do

  devise_for :users, class_name: 'FormUser', :controllers => { registrations: 'registrations',
                   omniauth_callbacks: 'omniauth_callbacks'}
  resources :admin_users, controller: 'users'
  resources :categories do
    collection do
      put :sort, to: 'categories#sort'
    end
    resources :posts, except: [:new, :create, :index] do
      resources :comments, only: [:create, :destroy]
    end
  end
  resources :posts, only: [:new, :create]
  resources :topics do
    resources :forum_posts, only: [:create, :destroy] do
      member do
        put :like, to: 'forum_posts#upvote'
        put :dislike, to: 'forum_posts#downvote'
      end
    end
  end
  get 'search', to: 'homes#search'
  root 'homes#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :topics , dependent: :destroy# forum posts
  has_many :posts, dependent: :destroy

  validates_presence_of :name
  validates_presence_of :priority
  validates_uniqueness_of :priority

  scope :first_eight_by_priority, -> { order('priority asc').first(8) }
  scope :rest_by_priority, -> { offset(8).order('priority asc') }
=begin
  scope :with_popular_posts, -> { joins(:posts).
     where('posts.id = (SELECT MAX(posts.id) FROM posts WHERE posts.category_id = categories.id)').
      group('categories.id')

  }
=end

  def self.first_post(name)
    find_by_name(name).posts.first
  end

  def last_activity
    self.posts.last.created_at
  end

  def has_posts?
    self.posts_count > 0
  end

  def posts_desc
    self.posts.order('created_at desc')
  end

  def last_10_except_this(topic_id)
    self.topics.where.not(id: topic_id).last(10)
  end



end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all.includes(:posts)
  end

  def show
    @posts = @category.posts_desc.paginate(:page => params[:page], :per_page => 5)
  end
  
  def new
    authorize Category
    @category = Category.new
  end
  
  def create
    @category = Category.new(category_params)
    @category.priority = Category.maximum(:priority) + 1
    authorize @category
    respond_to do |format|
      if @category.save
        format.html {redirect_to @category, notice: 'Successfully added new category'}
        format.js {  }
      else
        render 'new'
      end
    end
  end

  def edit
    authorize @category
  end

  def update
    authorize @category
    if @category.update(category_params)
      redirect_to @category, notice: 'Category successfully updated'
    else
      render 'edit'
    end
  end

  def destroy
    authorize @category
    @category.destroy
    redirect_to categories_path, notice: 'Category deleted'
  end

  def sort
    params[:order].each do |key, value|
      Category.friendly.find(value[:id]).update_attribute(:priority,value[:position])
    end
    render nothing: true
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.friendly.find(params[:id])
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper

  def cache_key_for_categories
    count ||= Category.count
    max_updated_at ||= Category.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "categories/all-#{count}-#{max_updated_at}"
  end

end

app/views/categories/_category.html.erb
<div>
  <h3><%= link_to category.name, category %></h3>
</div>

app/views/categories/_form.html.erb
<div class="row">
  <div class="col-md-6 form_div">
    <%= form_for(@category, remote: true) do |f| %>
        <% if @category.errors.any? %>
            <div class="form_errors">
              <h4> <%= pluralize(@category.errors.size, 'error')%> prohibited this data from being saved</h4>
              <ul>
                <% @category.errors.full_messages.each do |msg| %>
                    <li> <%= msg %> </li>
                <% end %>
              </ul>
            </div>
        <% end %>
        <div class="field">
          <%= f.label :name %>
          <%= f.text_field :name, placeholder: 'Category name' %>
        </div>
        <br/>
        <div class="actions">
          <%= f.submit  class: 'button_my' %>
        </div>
    <% end %>
    </div>


    <div style="display: none;" class="col-md-6 div_sort">
      <p>By default this will be category with the lowest priority. Change it of you want.</p>
      <p>When finished click: <%= link_to 'Done', categories_path%> </p>
        <div class="sortable">
        </div>
    </div>
</div>

app/views/categories/_sort.html.erb
<div data-id="<%= category.id %>" class="category_sort">
  <h4><%= category.name %></h4>
</div>

app/views/categories/create.js.erb
var elm = $('div.sortable');
elm.append(' <%= j render partial: 'sort', collection: Category.all, as: :category %>');
$('div.div_sort').show();
$('input#category_name').val('');
$('div.form_div').prepend('<div id="flash_notice">New category added successfully ' +
        '<span class="pull-right">x</span></div>');

app/views/categories/edit.html.erb
<h3>Edit Category</h3>
<hr class="line"/>
<%= render 'form' %>
<br/>
<%= link_to 'Back to all categories', categories_path %>

app/views/categories/index.html.erb
<h3>All Categories</h3>
<hr class="line"/>
<div class="main_content">
  <% @categories.each do |category| %>
    <h4> Category name: <%= link_to category.name, category %> </h4>
    <h5> Number of posts: <%=  category.posts_count %> </h5>
      <% if category.has_posts? %>
    <h5> Last post: <%=time_ago_in_words category.last_activity %> ago</h5>
          <% end %>
    <%= link_to 'Edit', edit_category_path(category)%> |
      <%= link_to 'Delete', category, method: :delete, data: {confirm: 'Are you sure?'} %>
      <hr/>
  <% end %>
</div>
<div class="sidebar">
  <%= button_to 'Create new category', new_category_path, {method: :get, class: 'button_my'}%>
  <%= render 'posts/sidebar' %>
</div>

app/views/categories/new.html.erb
<h3>New Category</h3>
<hr class="line"/>

<%= render 'form' %>

app/views/categories/show.html.erb
<h4 class="heading"> <strong>Category Archives: </strong> <%= @category.name %> </h4>
<hr class="line"/>
<div class="main_content">
  <div class="posts">
  <% if @category.posts.present? %>
    <%= render partial: 'posts/post', collection: @posts.with_first_image, as: :post %>
    <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
  <% else %>
    <h5>There are currently no posts in this category.</h5>
  <% end %>
  </div>
</div>
<div class="sidebar">
  <%= render 'posts/sidebar' %>
</div>