config/routes.rb
Rails.application.routes.draw do

  devise_for :users, class_name: 'FormUser', :controllers => { registrations: 'registrations',
                   omniauth_callbacks: 'omniauth_callbacks'}
  resources :admin_users, controller: 'users'
  resources :categories do
    collection do
      put :sort, to: 'categories#sort'
    end
    resources :posts, except: [:new, :create, :index] do
      resources :comments, only: [:create, :destroy]
    end
  end
  resources :posts, only: [:new, :create]
  resources :topics do
    resources :forum_posts, only: [:create, :destroy] do
      member do
        put :like, to: 'forum_posts#upvote'
        put :dislike, to: 'forum_posts#downvote'
      end
    end
  end
  get 'search', to: 'homes#search'
  root 'homes#index'

end

app/views/layouts/application.html+phone.erb
<!DOCTYPE html>
<html>
<head>
  <title>Website</title>
  <%= stylesheet_link_tag    'phone', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="header">
  <div class="extra_fields">
    <ul>
      <% if user_signed_in? %>
          <li> <strong> <%= current_user.name %> </strong> </li>
          <li> <%= link_to 'Logout', destroy_user_session_path, method: :delete %> </li>
          <li> <%= link_to 'RSS' %> </li>
      <% else %>
          <li> <%= link_to 'Log In', new_user_session_path %> </li>
          <li> <%= link_to 'Sign Up', new_user_registration_path %> </li>
      <% end %>
      <li style="float: right;"><a href="#">Last</a> </li>
    </ul>
  </div>
  <div class="banner"></div>
  <div class="navigation">
    <ul>
      <li> <%= link_to 'Home', posts_path, class: 'active' %> </li>
      <% Category.all.each do |category| %>
          <li> <%= link_to category.name, category %> </li>
      <% end %>
    </ul>
  </div>
</div>
<div class="container">
  <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
  <% end %>
  <%= yield %>
</div>
<div class="footer">
  <div id="company">
    <h3>Company</h3>
    <p>Curabitur non nulla sit amet nisl tempus convallis quis ac lectus. Cras ultricies ligula sed magna dictum porta. Proin eget tortor risus. Cras ultricies ligula sed magna dictum porta. Nulla porttitor accumsan tincidunt. Curabitur non nulla sit amet nisl tempus convallis quis ac lectus. Curabitur aliquet quam id dui posuere blandit. Nulla porttitor accumsan tincidunt. Curabitur aliquet quam id dui posuere blandit. Donec sollicitudin molestie malesuada.</p>
  </div>
  <div id="data">
    <h3>Navigation</h3>
    <ul>
      <li>Todo</li>
      <li>Make</li>
      <li>Dynamic</li>
      <li>Links</li>
    </ul>
  </div>
  <div id="data">
    <h3>Meta</h3>
    <ul>
      <li>Todo</li>
      <li>Make</li>
      <li>Dynamic</li>
      <li>Links</li>
    </ul>
  </div>
  <div id="data">
    <h3>Contacts</h3>
  </div>
</div>

</body>
</html>

app/views/layouts/application.html+tablet.erb
<!DOCTYPE html>
<html>
<head>
  <title>Website</title>
  <%= stylesheet_link_tag    'tablet', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="header">
  <div class="extra_fields">
    <ul>
      <% if user_signed_in? %>
          <li> <strong> <%= current_user.name %> </strong> </li>
          <li> <%= link_to 'Logout', destroy_user_session_path, method: :delete %> </li>
          <li> <%= link_to 'RSS' %> </li>
      <% else %>
          <li> <%= link_to 'Log In', new_user_session_path %> </li>
          <li> <%= link_to 'Sign Up', new_user_registration_path %> </li>
      <% end %>
      <li style="float: right;"><a href="#">Last</a> </li>
    </ul>
  </div>
  <div class="banner"></div>
  <div class="navigation">
    <ul>
      <li> <%= link_to 'Home', posts_path, class: 'active' %> </li>
      <% Category.all.each do |category| %>
          <li> <%= link_to category.name, category %> </li>
      <% end %>
    </ul>
  </div>
</div>
<div class="container">
  <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
  <% end %>
  <%= yield %>
</div>
<div class="footer">
  <div id="company">
    <h3>Company</h3>
    <p>Curabitur non nulla sit amet nisl tempus convallis quis ac lectus. Cras ultricies ligula sed magna dictum porta. Proin eget tortor risus. Cras ultricies ligula sed magna dictum porta. Nulla porttitor accumsan tincidunt. Curabitur non nulla sit amet nisl tempus convallis quis ac lectus. Curabitur aliquet quam id dui posuere blandit. Nulla porttitor accumsan tincidunt. Curabitur aliquet quam id dui posuere blandit. Donec sollicitudin molestie malesuada.</p>
  </div>
  <div id="data">
    <h3>Navigation</h3>
    <ul>
      <li>Todo</li>
      <li>Make</li>
      <li>Dynamic</li>
      <li>Links</li>
    </ul>
  </div>
  <div id="data">
    <h3>Meta</h3>
    <ul>
      <li>Todo</li>
      <li>Make</li>
      <li>Dynamic</li>
      <li>Links</li>
    </ul>
  </div>
  <div id="data">
    <h3>Contacts</h3>
  </div>
</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Website</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= cloudinary_js_config %>
</head>
<body>
<div class="header">
  <div class="extra_fields">
    <ul><%= cloudinary_js_config %>
      <% if user_signed_in? %>
          <li> <strong> <%= current_user.name %> </strong> </li>
          <li> <%= link_to 'Sign out', destroy_user_session_path, method: :delete %> </li>
          <% if current_user.moderator? %>
            <li> <%= link_to 'New Post', new_post_path %> </li>
          <% end %>
          <% if current_user.admin? %>
              <li> <%= link_to 'New Post', new_post_path %> </li>
              <li> <%= link_to 'Manage users', admin_users_path %> </li>
              <li> <%= link_to 'Categories', categories_path %> </li>
          <% end %>
      <% else %>
          <li> <%= link_to 'Sign In', new_user_session_path %> </li>
          <li> <%= link_to 'Sign Up', new_user_registration_path %> </li>
      <% end %>
      <li style="float: right;"><input type="text" id="query" placeholder="Search"/>  <%= link_to 'Search', search_path, {id: 'link_search'} %> </li>
    </ul>
  </div>
  <div class="banner">
    <%= image_tag 'banner7.png', width: '466px', height: '85px', alt: 'Free Website' %>
  </div>
      <div class="navigation">
        <ul class="main_nav">
          <li> <%= link_to 'Home', root_path, {class: set_class_if_root_page} %> </li>
              <% @categories_list[0..7].each do |category| %>
                <li> <%= link_to category.name, category, {class: set_class?(category.slug)} %> </li>
              <% end %>
              <% if @categories_list.size > 8 %>
                  <li>
                    <div class="dropdown">
                      <span class="dropdown-toggle" id="main_span" data-toggle="dropdown">Rest
                        <span class="caret"></span></span>
                      <ul class="dropdown-menu">
                        <% @categories_list[8..@categories_list.size].each do |category| %>
                            <li> <%= link_to category.name, category %> </li>
                        <% end %>
                      </ul>
                    </div>
                  </li>
              <% end %>
              <li> <%= link_to 'Forum', topics_path %> </li>
        </ul>
      </div>
</div>
<div class="container">
    <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}", class: 'flash_msg'%>
    <% end %>
    <%= yield %>
</div>
<div class="footer">
  <div id="company">
    <h3>Company</h3>
    <p>Curabitur non nulla sit amet nisl tempus convallis quis ac lectus. Cras ultricies ligula sed magna dictum porta. Proin eget tortor risus. Cras ultricies ligula sed magna dictum porta. Nulla porttitor accumsan tincidunt. Curabitur non nulla sit amet nisl tempus convallis quis ac lectus. Curabitur aliquet quam id dui posuere blandit. Nulla porttitor accumsan tincidunt. Curabitur aliquet quam id dui posuere blandit. Donec sollicitudin molestie malesuada.</p>
  </div>
  <div id="f_navigation">
    <h3>Navigation</h3>
    <ul>
      <li> <%= link_to 'Home', root_path %> </li>
      <% @categories_list[0..3].each do |category| %>
            <li> <%=link_to category.name, category %> </li>
      <% end %>
    </ul>
  </div>
  <div id="meta">
    <h3>Meta</h3>
    <ul>
      <li> <%= link_to 'Sign In', new_user_session_path %></li>
      <li> <%= link_to 'Sign Up', new_user_registration_path%> </li>
    </ul>
  </div>
  <div id="contacts">
    <h3>Contacts</h3>
    <div>
        <i class="fa fa-home" aria-hidden="true"></i><span>  Somewhere 231b, Some Street </span>
    </div>
    <div>
      <i class="fa fa-phone" aria-hidden="true"></i><span>  (00)454-454-454</span>
    </div>
    <div>
      <i class="fa fa-envelope" aria-hidden="true"></i><span>  someone@mail.com</span>
    </div>
  </div>
  <hr/>
  <p class="details">Free Website from Edis Veljačić</p>
</div>



</body>
</html>